import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { getProjectById } from "../../lib/projects";
import { getUserById } from "../../lib/users";
import style from "../../styles/ProjectDetailPage.module.css";

export default function Project() {
  const router = useRouter();
  const { id } = router.query;
  const [project, setProject] = useState(null);
  const [user, setUser] = useState(null);

  useEffect(() => {
    async function fetchData() {
      // project
      if (id == undefined || id == null) return;
      const project = await getProjectById(id);
      setProject(project);
    }
    fetchData();
  }, [id]);

  useEffect(() => {
    async function fetchData() {
      if (project?.uid == undefined || project?.uid == null) return;
      const user = await getUserById(project.uid);
      setUser(user);
      console.log(user);
    }
    fetchData();
  }, [project]);

  return (
    <>
      <Head>
        <title>Final Show - Project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {project != null && (
        <>
          <div className={style.banner_img}>
            <img src={project.previewImageUrl} alt={project.title} />
          </div>
          <div className={style.main_wrapper}>
            <div className={style.info_section}>
              <div className={style.user_details}>
                <div className="pfp">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="200"
                    height="200"
                    viewBox="0 0 338 338"
                  >
                    <g
                      id="Ellipse_6"
                      data-name="Ellipse 6"
                      fill="#bdbdda"
                      stroke="#707070"
                      strokeWidth="1"
                    >
                      <circle cx="169" cy="169" r="169" stroke="none" />
                      <circle cx="169" cy="169" r="168.5" fill="none" />
                    </g>
                    <path
                      id="Icon_awesome-robot"
                      data-name="Icon awesome-robot"
                      d="M0,106.916v53.458a13.35,13.35,0,0,0,13.365,13.365H26.729V93.552H13.365A13.35,13.35,0,0,0,0,106.916ZM193.786,40.094H147.01V13.365a13.365,13.365,0,1,0-26.729,0V40.094H73.505A33.4,33.4,0,0,0,40.094,73.505V187.1a26.754,26.754,0,0,0,26.729,26.729H200.468A26.754,26.754,0,0,0,227.2,187.1V73.505A33.4,33.4,0,0,0,193.786,40.094Zm-86.87,133.646H80.187V160.375h26.729ZM93.552,123.622a16.706,16.706,0,1,1,16.706-16.706A16.7,16.7,0,0,1,93.552,123.622Zm53.458,50.117H120.281V160.375H147.01Zm40.094,0H160.375V160.375H187.1Zm-13.365-50.117a16.706,16.706,0,1,1,16.706-16.706A16.7,16.7,0,0,1,173.739,123.622Zm80.187-30.07H240.562v80.187h13.365a13.35,13.35,0,0,0,13.365-13.365V106.916A13.35,13.35,0,0,0,253.926,93.552Z"
                      transform="translate(35.355 62.083)"
                    />
                  </svg>
                </div>
                <h1
                  onClick={() => {
                    router.push(`/profile/${user.uid}`);
                  }}
                >
                  {user && user.username}
                </h1>
                <p>Multimedia & Creative Technologie - Jaar 2</p>
                <p>USER SOCIALS</p>
              </div>
              <div className={style.project_details}>
                <div>
                  <h1>{project.title}</h1>
                  <h3>{project.category}</h3>
                </div>
                <p>{project.description}</p>
                <p className={style.tags}>{project.tags.join(" / ")}</p>
              </div>
            </div>
          </div>
        </>
      )}
    </>
  );
}
