import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import styles from "../../styles/Awards.module.css";
import DottedLine from '../../components/DottedLine';
import UnderConstruction from '../../components/UnderConstruction';
import ButtonPink from '../../components/ButtonPink';
import AwardBanner from '../../components/AwardBanner';

export default function Award() {
    const router = useRouter();
    const { id } = router.query;

    return (
        <>
            <Head>
                <title>Final Show - Award {id}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
      
<main className='max-w-7xl mx-auto px-4 sm:px-6 lg:px-8'>
<header>
<AwardBanner />
    </header>
<div>
    <div className={styles.awardProjects}>
<h1>
    Projects
    </h1>
    <ButtonPink title="Add" color='white' />
    </div>
    </div>

    <div className='customGrid'></div>

</main> 
        </>
    );
}
