import Head from "next/head";
import React, { useContext, useEffect, useState } from "react";
import AddAwardButton from "../../components/AddAwardButton";
import AwardCard from "../../components/AwardCard";
import UnderConstruction from "../../components/UnderConstruction";
import { UserContext } from "../../lib/context";
import styles from "../../styles/Awards.module.css";
import SliderComponent from "../../components/SliderComponent";
import TitleComponent from "../../components/TitleComponent";

export default function Awards() {
  const { user } = useContext(UserContext);
  const [userData, setUserData] = useState(null);
  const [awards, setAwards] = useState([]);

  useEffect(() => {
    const fetchAwardData = async () => {
      try {
        const data = await fetch("/api/awards");
        const dataL = await data.json();
        setAwards(dataL);
      } catch (e) {
        console.error(e);
      }
    };

    const fetchUserData = async () => {
      try {
        if (!user) return;
        const response = await fetch(`/api/users/${user.uid}`);
        const data = await response.json();
        setUserData(data);
      } catch (error) {
        console.error("Error fetching award:", error);
      }
    };

    fetchAwardData();
    fetchUserData();
  }, [user]);

  return (
    <>
      <Head>
        <title>Final Show - Awards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {userData && userData.role === "admin" && (
        <div>
          <AddAwardButton />
        </div>
      )}

      <main>
        <div className="containerWidth">
          <div className={styles.awardsAwardsContainer}>
            <div className={styles.awardsDesktop}>
              <SliderComponent awards={awards} />
            </div>
          </div>
          <div className={styles.awardsMobile}>
            {awards.map((award) => (
              <AwardCard award={award} key={award.id} />
            ))}
          </div>
          <div className={styles.awardsPastAwardsContainer}>
            <TitleComponent title={"Past Awards"} />
            <div className={styles.awardsDesktop}>
              <SliderComponent awards={awards} />
            </div>
          </div>
          <div className={styles.awardsMobile}>
            {awards.map((award) => (
              <AwardCard award={award} key={award.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
