import Head from "next/head";
import React, { useState, useEffect,useContext } from "react";
import UnderConstruction from "../../components/UnderConstruction";
import AwardCard from "../../components/AwardCard";
import { UserContext } from '../../lib/context';
import AddAwardButton from "../../components/AddAwardButton";
export default function Awards() {
   const { user } = useContext(UserContext);
   const [userData, setUserData] = useState();
  const [awards, setAwards] = useState([]);

  useEffect(() => {
    const fetchAwardData = async () => {
      console.log("before fetch");
      try {
        const data = await fetch("/api/awards");
        const dataL = await data.json();
        console.log(dataL);
        setAwards(dataL);
      } catch (e) {
        console.error(e);
      }
    };

    const fetchUserData = async () => {
      console.log("before fetch");
      try {
        const response = await fetch(`/api/users/${user.uid}`);
        const data = await response.json();
        console.log(data); // Check if the data is correctly fetched
        setUserData(data);
      } catch (error) {
        console.error("Error fetching award:", error);
      }
    };

    fetchAwardData();
    fetchUserData();
  },  [user && user.uid]);

  useEffect(() => {
    console.log(userData); // Check the updated value of userData
  }, [userData]);


  return (
    <>
      <Head>
        <title>Final Show - Awards</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      
      {userData && userData.role === "admin" && (
        <div>
          <AddAwardButton />
        </div>
      )}

      <div className="flex justify-center mt-10 h-350px">
        <div className="flex w-full max-w-screen-xl overflow-x-scroll gap-5 h-full">
          {awards.map((award) => (
            <div className="flex-shrink-0 w-1/3 h-full" key={award.id}>
              <AwardCard award={award} key={award.id} />
            </div>
          ))}
        </div>
      </div>
    </>
  );
}