import Head from 'next/head';
import UnderConstruction from '../../components/UnderConstruction';
import UploadAwardForm from '../../components/UploadAwardForm';


const upload = () => {
  return (
    <>
    <Head>
        <title>Final Show - Upload Award</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
rel="stylesheet"></link>
    </Head>
   
    <div className='flex items-center justify-center'>
        <UploadAwardForm/>
    </div>
  
</>
  )
}

export default upload