import Head from 'next/head';
import UnderConstruction from '../components/UnderConstruction';

export default function Login() {
    return (
        <>
            <Head>
                <title>Final Show - Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <UnderConstruction />;
        </>
    );
}
