import Head from "next/head";
import UnderConstruction from "../components/UnderConstruction";
import LoginForm from "../components/LoginForm";
import { useContext } from "react";
import { UserContext } from "../lib/context";
import SignedIn from "../components/SignedIn";
import { useRouter } from "next/router";

export default function Register() {
  const { user } = useContext(UserContext);
  const router = useRouter();

  const redirect = () => {
    router.push("/");
    return null;
  };

  return (
    <>
      <Head>
        <title>Final Show - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-center">
        {user ? redirect() : <LoginForm />}
      </div>
    </>
  );
}
